fos_rest:
    param_fetcher_listener: force
    routing_loader: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json', prefer_extension: false }
    body_listener:
        enabled: true
    exception:
        enabled: true
        messages:
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': true
        codes:
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': 401
        #exception_controller: 'fos_rest.exception.controller:showAction'